16h17-done-mo_ta_yeu_cau_de_tai
truongduchuy910/PBL6 pull request #2
Opened 2021-09-15 09:18 UTC by trandiepphuong

2021-09-15 09:22 UTC, huytn-1183 commented
Chuẩn hoá lại markdown giúp ta. Còn view lên web sau này báo cáo lun.

2021-09-15 09:25 UTC, truongduchuy910 requested changes

2021-09-15 09:25 UTC, truongduchuy910 commented on describe-requirement.md
> +# Mô tả yêu cầu của đề tài
Định dạng lại markdown giúp ta vì docs còn view lên web nữa.

2021-09-15 09:52 UTC, truongduchuy910 commented
Có một số vấn đề sau:

- Không sử dụng HTML trong tài liệu
- Gắng link về trang chủ ở đầu tài liệu ```[Trang chủ](/)```
- Gắng các bài liên quan ở chân tài liệu

2021-09-16 02:06 UTC, truongduchuy910 commented
Dời và đổi tên file vào /docs/requirement/md nha!

2021-09-16 13:14 UTC, merged